### ISSUE TITLE
No result anymore

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/search.cocoapods.org#112] opened 2017-05-27 06:34 UTC
I don't get any result anymore for any search.
Example: https://cocoapods.org/?q=alamofire
![screen shot 2017-05-27 at 14 33 20](https://cloud.githubusercontent.com/assets/839992/26518760/7e4b84c4-42e9-11e7-81c0-87e348175086.png)

And on https://search.cocoapods.org/ I get:
>Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by orta** [comment] 2017-05-27 10:34
Thanks for the issue, it's a dupe of
https://github.com/CocoaPods/CocoaPods/issues/6591#issuecomment-304304922

On May 27, 2017 07:34, "Antoine Cœur" <notifications@github.com> wrote:

I don't get any result anymore for any search.
Example: https://cocoapods.org/?q=alamofire
[image: screen shot 2017-05-27 at 14 33 20]
<https://cloud.githubusercontent.com/assets/839992/26518760/7e4b84c4-42e9-11e7-81c0-87e348175086.png>

And on https://search.cocoapods.org/ I get:

Application error
An error occurred in the application and your page could not be served. If
you are the application owner, check your logs for details.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CocoaPods/search.cocoapods.org/issues/112>, or mute the
thread

**Comment by Coeur** [comment] 2017-05-28 07:59
OK. Then, just to quote the relevant part of the comment:

> it went away after about two or three hours. Try different time window during the day. I suspect they probably change the way they run their updates and while it's indexing the repositories that they are only partially usable

Too bad it took that long.

**Comment by orta** [comment] 2017-05-28 10:05
Cool, as this is a known issue there's no point in keeping around a duplicate though 👍

**Closed by orta** 2017-05-28 10:05 UTC
